run:
  timeout: 3m

linters:
  enable:
    # Bugs & correctness
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck

    # Code quality
    - unused
    - gosimple
    - gocritic
    - revive
    - unconvert
    - misspell

    # Security
    - gosec

    # SQL injection prevention (relevant for raw SQL repos)
    - sqlclosecheck

    # Style consistency
    - gofmt
    - goimports

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # too noisy, low value
  revive:
    rules:
      - name: exported
        disabled: true # we don't enforce doc comments on exports
      - name: unexported-return
        disabled: true
  gocritic:
    disabled-checks:
      - ifElseChain
      - singleCaseSwitch
  gosec:
    excludes:
      - G104 # unhandled errors — already covered by errcheck

issues:
  exclude-rules:
    # Test files can be more relaxed
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0
